"""create pending_notes table

Revision ID: daf904df7559
Revises: 7fd0d6c70b7f
Create Date: 2026-07-02 16:40:51.730244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'daf904df7559'
down_revision: Union[str, Sequence[str], None] = '7fd0d6c70b7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # postgresql.ENUM(create_type=False): the `notetype` enum already exists (created by the
    # notes-table migration). Without create_type=False, op.create_table re-emits
    # CREATE TYPE notetype and fails. The generic sa.Enum does not honor this flag reliably —
    # the PostgreSQL-specific type does.
    op.create_table('pending_notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('note_type', postgresql.ENUM('technical_note', 'command', 'error_fix', 'project_note', 'concept', 'question', name='notetype', create_type=False), nullable=False),
    sa.Column('tool', sa.String(length=100), nullable=True),
    sa.Column('project', sa.String(length=200), nullable=True),
    sa.Column('topic', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pending_notes')
    # ### end Alembic commands ###
